---
params:
  asof: ""
title: Daily Media Digest
editor_options:
  chunk_output_type: console
output: 
  html_document:
    theme: flatly
    highlight: tango
    self_contained: false
    lib_dir: daily/rmdlib
    toc: true
    toc_depth: 2
    includes:
        in_header: ../header.html
        after_body: ../footer.html
---

```{r, init_chunk, echo = FALSE, message = FALSE, warning = FALSE}
library('RODBC')
library('DBI')
library('RSQLite')
library('jsonlite')
library('tidyverse')
library('httr2')

options(stringsAsFactors = FALSE)
options("scipen"=100)

asof <- as.Date(params$asof)
if(is.na(asof)){
  asof <- Sys.Date()
}

mediaDbName <- "/mnt/icelandD/recoll/MEDIA.db"
newsDbName <- "/mnt/icelandD/recoll/NEWS.db"

eqLocLocal <- "../../reports02/eq-in/risk"
eqLocRemote <- "https://stockviz.github.io/reports02/eq-in/risk"

mydb <- dbConnect(RSQLite::SQLite(), dbname = mediaDbName, flags = RSQLite::SQLITE_RO)
aiSummaries1 <- dbGetQuery(mydb, "SELECT * FROM META WHERE UPLOAD_DT = $1 
                           and SUMMARY is not NULL 
                           and SYMBOLS is not NULL 
                           order by TS desc", 
                          params=list(strftime(asof, "%Y%m%d")))
dbDisconnect(mydb)

mydb <- dbConnect(RSQLite::SQLite(), dbname = newsDbName, flags = RSQLite::SQLITE_RO)
aiSummaries2 <- dbGetQuery(mydb, "SELECT * FROM ARTICLES WHERE PUB_DT = $1 
                           and SUMMARY is not NULL 
                           and TAGS is not NULL 
                           order by PUB_TS desc", 
                          params=list(strftime(asof, "%Y%m%d")))
dbDisconnect(mydb)

aiSummaries <- tibble()

for(i in 1:nrow(aiSummaries1)){
  aiSummaries <- rbind(aiSummaries, c(
    aiSummaries1$TITLE[i],
    aiSummaries1$SYMBOLS[i],
    aiSummaries1$SUMMARY[i],
    aiSummaries1$SRC[i],
    paste0("https://youtu.be/", aiSummaries1$ID[i]),
    aiSummaries1$TS[i],
    aiSummaries1$DURATION[i]
  ))
}

for(i in 1:nrow(aiSummaries2)){
  aiSummaries <- rbind(aiSummaries, c(
    aiSummaries2$TITLE[i],
    aiSummaries2$SYMBOLS[i],
    aiSummaries2$SUMMARY[i],
    NA,
    aiSummaries2$URL[i],
    aiSummaries1$TS[i],
    NA
  ))
}

colnames(aiSummaries) <- c("TITLE", "SYMBOLS", "SUMMARY", "SRC", "LINK", "TS", "DURATION")

aiSummaries$TS <- as.numeric(aiSummaries$TS)
aiSummaries <- aiSummaries |> arrange(desc(TS))

```

---
subtitle: `r asof`
---

```{r, ai_summary_chunk, echo = FALSE, results='asis', message = FALSE, warning = FALSE, fig.height=12, fig.width=12}
if(nrow(aiSummaries) == 0) q()

for(i in 1:nrow(aiSummaries)){
  cat("## ", aiSummaries$TITLE[i], "\n\n")
  
  syms <- jsonlite::fromJSON(aiSummaries$SYMBOLS[i])
  
  if(length(syms) > 0){
    for(j in 1:length(syms)){
      if(length(syms[j]) == 0) next
      
      symName <- gsub("[^[:alnum:] ]| ", "", syms[j])
      if(length(symName) == 0) next
      
      if(file.exists(paste0(eqLocLocal, "/in.", symName, ".html"))){
        link <- paste0(eqLocRemote, "/in.", symName, ".html")
        cat(paste0("[", syms[j], "](", link, ") "))
      } else {
        cat("`", syms[j], "` ")
      }
      
    }
    cat("\n\n")
  }
  
  cat(aiSummaries$SUMMARY[i])
  cat("\n\n")
  if(!is.na(aiSummaries$SRC[i])){
    cat(paste0("*", 
             aiSummaries$SRC[i], ": ",
             aiSummaries$LINK[i], " ",
             strftime(as.POSIXct(aiSummaries$TS[i]), '%H:%M'), " ",
             "(", aiSummaries$DURATION[i], "s) ",
              "*"))
  } else {
    artSrc <- str_remove(url_parse(aiSummaries$LINK[i])$hostname, "www.")
    cat(paste0("*[", 
             artSrc, "](",
             aiSummaries$LINK[i], ") ",
             strftime(as.POSIXct(aiSummaries$TS[i]), '%H:%M'),
              "*"))  
  }
  
  cat("\n\n\n\n")
}

```